name: JoinDex
version: 1.0.0
main: JoinDex\Main
api: 5.0.0
author: IndexDev
description: This plugin welcomes players upon entering!

commands:
  setwelcome:
    description: "Set the welcome message"
    usage: "/setwelcome <tipo> <mensaje>"
    permission: "welcomemessage.set"
    
permissions:
  welcomemessage.set:
    description: "Allows you to change the welcome messages"
    default: op
